<x-layouts::app title="Create employment contract">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><h1 class="h3 mb-1">Create employment contract</h1><p class="text-body-secondary mb-0">Save a draft and submit it for approval.</p></div><a class="btn btn-outline-secondary" href="{{ route('contracts.index') }}"><i class="fa-solid fa-arrow-left me-1"></i>Back to contracts</a></div>
    @if ($errors->any())<div class="alert alert-danger"><ul class="mb-0 ps-3">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form class="contract-create-form" method="POST" action="{{ route('contracts.store') }}" enctype="multipart/form-data">@csrf
        @if ($renewal)<input type="hidden" name="previous_contract_id" value="{{ $renewal->id }}"><div class="alert alert-info">Renewing contract {{ $renewal->contract_number }}. The new term must start after {{ $renewal->end_date->format('d/m/Y') }}.</div>@endif
        <div class="card mb-3"><div class="card-header">Employee and contract</div><div class="card-body row g-3"><div class="col-md-6"><label class="form-label">Employee <span class="text-danger">*</span></label><select class="form-select" name="employee_id" required><option value="">Select employee</option>@foreach ($employees as $employee)<option value="{{ $employee->id }}" @selected(old('employee_id', $renewal?->employee_id) == $employee->id)>{{ $employee->employee_code }} — {{ $employee->full_name_km ?: $employee->full_name_en }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Contract number <span class="text-danger">*</span></label><input class="form-control" name="contract_number" value="{{ old('contract_number') }}" required></div><div class="col-md-6"><label class="form-label">Contract type <span class="text-danger">*</span></label><select class="form-select" name="type" required><option value="fdc" @selected(old('type', $renewal ? 'fdc' : '') === 'fdc')>FDC — fixed duration</option><option value="udc" @selected(old('type') === 'udc')>UDC — open-ended</option><option value="probation" @selected(old('type') === 'probation')>Probation</option><option value="apprenticeship" @selected(old('type') === 'apprenticeship')>Apprenticeship</option><option value="internship" @selected(old('type') === 'internship')>Internship</option></select></div><div class="col-md-6"><label class="form-label">Signed document (PDF, max. 10 MB)</label><input class="form-control" type="file" name="document" accept=".pdf"></div></div></div>
        <div class="card mb-3"><div class="card-header">Term and probation</div><div class="card-body row g-3"><div class="col-md-4"><label class="form-label">Start date</label><input class="form-control" type="date" name="start_date" value="{{ old('start_date', $renewal?->end_date?->copy()->addDay()->toDateString()) }}" required></div><div class="col-md-4"><label class="form-label">End date</label><input class="form-control" type="date" name="end_date" value="{{ old('end_date') }}"></div><div class="col-md-4"><label class="form-label">Signed date</label><input class="form-control" type="date" name="signed_at" value="{{ old('signed_at') }}"></div><div class="col-md-6"><label class="form-label">Probation category</label><select class="form-select" name="probation_category"><option value="">Not applicable</option><option value="regular" @selected(old('probation_category') === 'regular')>Regular</option><option value="specialized" @selected(old('probation_category') === 'specialized')>Specialized</option><option value="non_specialized" @selected(old('probation_category') === 'non_specialized')>Non-specialized</option></select></div><div class="col-md-6"><label class="form-label">Probation end date</label><input class="form-control" type="date" name="probation_end_date" value="{{ old('probation_end_date') }}"></div></div></div>
        <div class="card"><div class="card-header">Salary and working time</div><div class="card-body row g-3"><div class="col-md-4"><label class="form-label">Salary amount</label><input class="form-control" type="number" step="0.01" min="0" name="salary_amount" value="{{ old('salary_amount', $renewal?->salary_amount) }}" required></div><div class="col-md-4"><label class="form-label">Currency</label><select class="form-select" name="salary_currency"><option value="USD" @selected(old('salary_currency', $renewal?->salary_currency ?? 'USD') === 'USD')>USD</option><option value="KHR" @selected(old('salary_currency', $renewal?->salary_currency) === 'KHR')>KHR</option></select></div><div class="col-md-4"><label class="form-label">Pay type</label><select class="form-select" name="pay_type"><option value="monthly" @selected(old('pay_type', $renewal?->pay_type ?? 'monthly') === 'monthly')>Monthly</option><option value="daily" @selected(old('pay_type') === 'daily')>Daily</option><option value="hourly" @selected(old('pay_type') === 'hourly')>Hourly</option></select></div><div class="col-md-6"><label class="form-label">Work hours per day</label><input class="form-control" type="number" step="0.25" min="1" max="24" name="work_hours_per_day" value="{{ old('work_hours_per_day', $renewal?->work_hours_per_day ?? 8) }}" required></div><div class="col-md-6"><label class="form-label">Work days per week</label><input class="form-control" type="number" step="0.5" min="1" max="7" name="work_days_per_week" value="{{ old('work_days_per_week', $renewal?->work_days_per_week ?? 6) }}" required></div></div></div>
        <div class="form-page-actions d-flex justify-content-end gap-2 pt-3"><a class="btn btn-light" href="{{ route('contracts.index') }}">Cancel</a><button class="btn btn-primary" type="submit"><i class="fa-solid fa-paper-plane me-1"></i>Save and submit</button></div>
    </form>
</x-layouts::app>
