<x-layouts::app title="Manage announcements">
    <x-workspace-command-bar title="Manage announcements" icon="fa-bullhorn">
        <x-slot:filters><form method="GET" class="reference-filter-form"><div class="input-group reference-search"><span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search announcement" hx-get="{{ request()->url() }}" hx-target="[data-list-container]" hx-swap="outerHTML" hx-push-url="false" hx-trigger="keyup changed delay:500ms"></div><button class="btn btn-primary reference-search-button">Search</button></form></x-slot:filters>
        <x-slot:actions><x-list-actions :add-modal="auth()->user()->can('announcement.manage') ? 'createAnnouncement' : null" add-label="Add announcement" /></x-slot:actions>
    </x-workspace-command-bar>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="reference-list" data-list-container><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-3">Announcement</th><th>Audience</th><th>Publish / expiry</th><th>Status</th><th>Acknowledged</th><th class="text-end pe-3">Actions</th></tr></thead><tbody>
        @forelse($announcements as $item)<tr><td class="ps-3"><div class="fw-semibold">{{ $item->title }} @if($item->is_pinned)<i class="fa-solid fa-thumbtack text-primary"></i>@endif @if($item->is_urgent)<span class="badge text-bg-danger">Urgent</span>@endif</div><small class="text-body-secondary">{{ str($item->content)->limit(100) }}</small></td><td>{{ str($item->audience_type)->title() }}</td><td>{{ $item->published_at?->format('d M Y H:i') ?: 'Draft' }}<small class="d-block text-body-secondary">Expires: {{ $item->expires_at?->format('d M Y') ?: 'Never' }}</small></td><td><span class="badge text-bg-{{ $item->published_at && $item->published_at->isPast() ? 'success' : 'secondary' }}">{{ !$item->published_at ? 'Draft' : ($item->published_at->isFuture() ? 'Scheduled' : 'Published') }}</span></td><td>{{ $item->requires_acknowledgement ? $item->acknowledgements_count : 'Not required' }}</td><td class="text-end pe-3">@if(!$item->published_at)<form class="d-inline" method="POST" action="{{ route('announcements.publish', $item) }}">@csrf<button class="btn btn-action-link btn-sm" type="submit"><i class="fa-solid fa-paper-plane"></i><span>Publish</span></button></form>@endif<button class="btn btn-action-link btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#edit{{ $item->id }}"><i class="fa-solid fa-pen"></i><span>Edit</span></button><form class="d-inline" method="POST" action="{{ route('announcements.destroy', $item) }}" data-confirm="Archive this announcement?">@csrf @method('DELETE')<button class="btn btn-action-link btn-sm text-danger" type="submit"><i class="fa-solid fa-box-archive"></i><span>Archive</span></button></form></td></tr>
        @empty<tr><td colspan="6" class="py-5 text-center text-body-secondary">No announcements found.</td></tr>@endforelse
    </tbody></table></div><x-pagination-footer :paginator="$announcements" /></div>

    @can('announcement.manage')
        <div class="modal fade" id="createAnnouncement" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('announcements.store') }}">@csrf<div class="modal-header"><h2 class="modal-title fs-5">Create announcement</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><x-announcement-fields :branches="$branches" :departments="$departments" /><label class="form-check mt-3"><input class="form-check-input" type="checkbox" name="publish_now" value="1" checked><span class="form-check-label">Publish now (uncheck to use scheduled publish time)</span></label></div><x-form-save-actions :allow-save-new="true" save-label="Save & close" new-label="Save & new" /></form></div></div>
        @foreach($announcements as $item)<div class="modal fade" id="edit{{ $item->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('announcements.update', $item) }}">@csrf @method('PUT')<div class="modal-header"><h2 class="modal-title fs-5">Edit announcement</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><x-announcement-fields :branches="$branches" :departments="$departments" :announcement="$item" /></div><x-form-save-actions save-label="Save & close" /></form></div></div>@endforeach
    @endcan
</x-layouts::app>