<?php
use App\Models\Announcement; use App\Models\Branch; use App\Models\Department;
use Livewire\Attributes\Computed; use Livewire\Attributes\Title; use Livewire\Component;
new #[Title('សេចក្តីជូនដំណឹង')] class extends Component {
 public string $title='',$content='',$audience='all',$branchId='',$departmentId='',$publishAt='',$expiresAt=''; public bool $pinned=false;
 public function mount():void{$this->publishAt=now()->format('Y-m-d\TH:i');}
 #[Computed] public function items(){return Announcement::latest()->limit(100)->get();} #[Computed] public function branches(){return Branch::orderBy('name')->get();} #[Computed] public function departments(){return Department::orderBy('name')->get();}
 public function save():void{abort_unless(auth()->user()->can('announcement.manage'),403);$d=$this->validate(['title'=>'required|string|max:180','content'=>'required|string|max:10000','audience'=>'required|in:all,branch,department','branchId'=>'nullable|required_if:audience,branch|exists:branches,id','departmentId'=>'nullable|required_if:audience,department|exists:departments,id','publishAt'=>'required|date','expiresAt'=>'nullable|date|after:publishAt']);Announcement::create(['company_id'=>auth()->user()->employee?->company_id ?? \App\Models\Company::query()->value('id'),'title'=>$d['title'],'content'=>$d['content'],'audience_type'=>$d['audience'],'branch_id'=>$d['audience']==='branch'?$d['branchId']:null,'department_id'=>$d['audience']==='department'?$d['departmentId']:null,'published_at'=>$d['publishAt'],'expires_at'=>$d['expiresAt']?:null,'created_by'=>auth()->id(),'is_pinned'=>$this->pinned]);$this->reset(['title','content','branchId','departmentId','expiresAt','pinned']);unset($this->items);}
}; ?>
<div class="space-y-6"><div><flux:heading size="xl">គ្រប់គ្រងសេចក្តីជូនដំណឹង</flux:heading><flux:subheading>ផ្សព្វផ្សាយតាមក្រុមហ៊ុន សាខា ឬផ្នែក</flux:subheading></div><form wire:submit="save" class="grid gap-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900 md:grid-cols-2 xl:grid-cols-3"><flux:input wire:model="title" label="ចំណងជើង *"/><flux:select wire:model.live="audience" label="អ្នកទទួល *"><option value="all">គ្រប់គ្នា</option><option value="branch">តាមសាខា</option><option value="department">តាមផ្នែក</option></flux:select>@if($audience==='branch')<flux:select wire:model="branchId" label="សាខា *"><option value="">ជ្រើសរើស</option>@foreach($this->branches as $x)<option value="{{$x->id}}">{{$x->name}}</option>@endforeach</flux:select>@elseif($audience==='department')<flux:select wire:model="departmentId" label="ផ្នែក *"><option value="">ជ្រើសរើស</option>@foreach($this->departments as $x)<option value="{{$x->id}}">{{$x->name}}</option>@endforeach</flux:select>@endif<div class="md:col-span-2 xl:col-span-3"><flux:textarea wire:model="content" label="ខ្លឹមសារ *" rows="4"/></div><flux:input wire:model="publishAt" type="datetime-local" label="ពេលផ្សាយ *"/><flux:input wire:model="expiresAt" type="datetime-local" label="ផុតកំណត់"/><flux:checkbox wire:model="pinned" label="បិទភ្ជាប់ខាងលើ"/><div class="md:col-span-2 xl:col-span-3 flex justify-end"><flux:button type="submit" variant="primary">ផ្សព្វផ្សាយ</flux:button></div></form><div class="grid gap-4 lg:grid-cols-2">@foreach($this->items as $x)<div class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><div class="flex justify-between"><flux:heading>{{$x->title}}</flux:heading><flux:badge>{{$x->audience_type}}</flux:badge></div><p class="mt-2 line-clamp-3 text-sm text-zinc-600 dark:text-zinc-300">{{$x->content}}</p><div class="mt-3 text-xs text-zinc-500">{{$x->published_at?->format('d/m/Y H:i')}}</div></div>@endforeach</div></div>
