<?php

use App\Models\Employee;
use App\Models\Task;
use App\Services\TaskWorkflowService;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Title;
use Livewire\Component;
use Livewire\WithPagination;

new #[Title('គ្រប់គ្រងកិច្ចការ')] class extends Component
{
    use WithPagination;
    public bool $showForm=false;
    public string $search=''; public string $status=''; public string $employeeId='';
    public string $title=''; public string $description=''; public string $priority='medium';
    public string $startDate=''; public string $dueDate=''; public array $notes=[]; public array $cancelReasons=[];
    public function mount(): void { abort_unless(auth()->user()?->can('task.view'),403); $this->startDate=now()->toDateString(); }
    #[Computed] public function tasks(){return Task::query()->with('employee')->when($this->search,function($q){$t='%'.$this->search.'%';$q->where(fn($q)=>$q->where('title','like',$t)->orWhereHas('employee',fn($e)=>$e->where('full_name_km','like',$t)->orWhere('employee_code','like',$t)));})->when($this->status,fn($q)=>$this->status==='overdue'?$q->whereNotIn('status',['verified','cancelled'])->whereDate('due_date','<',today()):$q->where('status',$this->status))->latest('id')->paginate(20);}
    #[Computed] public function employees(){return Employee::query()->active()->orderBy('employee_code')->get();}
    public function save():void{abort_unless(auth()->user()->can('task.assign'),403);$d=$this->validate(['employeeId'=>['required','exists:employees,id'],'title'=>['required','string','max:180'],'description'=>['nullable','string','max:3000'],'priority'=>['required',Rule::in(['low','medium','high','urgent'])],'startDate'=>['required','date'],'dueDate'=>['required','date','after_or_equal:startDate']]);$e=Employee::findOrFail($d['employeeId']);Task::create(['company_id'=>$e->company_id,'assigned_by'=>auth()->id(),'assigned_to'=>$e->id,'title'=>$d['title'],'description'=>$d['description']?:null,'priority'=>$d['priority'],'start_date'=>$d['startDate'],'due_date'=>$d['dueDate']]);$this->reset(['showForm','employeeId','title','description','dueDate']);unset($this->tasks);session()->flash('success','បានប្រគល់កិច្ចការ។');}
    public function verify(int $id,bool $approved,TaskWorkflowService $s):void{abort_unless(auth()->user()->can('task.verify'),403);try{$s->verify(Task::findOrFail($id),auth()->user(),$approved,$this->notes[$id]??null);}catch(\DomainException $e){$this->addError('workflow',$e->getMessage());return;}unset($this->tasks,$this->notes[$id]);}
    public function cancel(int $id,TaskWorkflowService $s):void{abort_unless(auth()->user()->can('task.cancel'),403);try{$s->cancel(Task::findOrFail($id),auth()->user(),$this->cancelReasons[$id]??'');}catch(\DomainException $e){$this->addError("cancelReasons.$id",$e->getMessage());return;}unset($this->tasks,$this->cancelReasons[$id]);}
}; ?>
<div class="space-y-6">
<div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><flux:heading size="xl">គ្រប់គ្រងកិច្ចការ</flux:heading><flux:subheading>ប្រគល់ តាមដាន និងផ្ទៀងផ្ទាត់កិច្ចការបុគ្គលិក</flux:subheading></div>@can('task.assign')<flux:button variant="primary" icon="plus" wire:click="$set('showForm',true)">ប្រគល់កិច្ចការ</flux:button>@endcan</div>
@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-green-800">{{session('success')}}</div>@endif @error('workflow')<div class="text-red-600">{{$message}}</div>@enderror
@if($showForm)<form wire:submit="save" class="grid gap-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900 sm:grid-cols-2 xl:grid-cols-3"><flux:select wire:model="employeeId" label="បុគ្គលិក *"><option value="">ជ្រើសរើស</option>@foreach($this->employees as $e)<option value="{{$e->id}}">{{$e->employee_code}} — {{$e->full_name_km?:$e->full_name_en}}</option>@endforeach</flux:select><flux:input wire:model="title" label="ចំណងជើង *"/><flux:select wire:model="priority" label="អាទិភាព *"><option value="low">ទាប</option><option value="medium">មធ្យម</option><option value="high">ខ្ពស់</option><option value="urgent">បន្ទាន់</option></flux:select><flux:input wire:model="startDate" type="date" label="ថ្ងៃចាប់ផ្តើម *"/><flux:input wire:model="dueDate" type="date" label="ថ្ងៃកំណត់ *"/><div class="sm:col-span-2 xl:col-span-3"><flux:textarea wire:model="description" label="ពិពណ៌នា" rows="2"/></div><div class="flex justify-end gap-2 sm:col-span-2 xl:col-span-3"><flux:button type="button" variant="ghost" wire:click="$set('showForm',false)">បោះបង់</flux:button><flux:button type="submit" variant="primary">រក្សាទុក</flux:button></div></form>@endif
<div class="grid gap-3 sm:grid-cols-[1fr_220px]"><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="ស្វែងរកកិច្ចការ ឬបុគ្គលិក..."/><flux:select wire:model.live="status"><option value="">ស្ថានភាពទាំងអស់</option><option value="not_started">មិនទាន់ចាប់ផ្តើម</option><option value="in_progress">កំពុងធ្វើ</option><option value="waiting_verification">រង់ចាំផ្ទៀងផ្ទាត់</option><option value="verified">បានបញ្ចប់</option><option value="overdue">ហួសកំណត់</option><option value="cancelled">បានលុបចោល</option></flux:select></div>
<div class="overflow-hidden rounded-2xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-zinc-200 dark:divide-zinc-700"><thead class="bg-zinc-50 dark:bg-zinc-800/60"><tr class="text-left text-sm"><th class="px-5 py-3">កិច្ចការ/បុគ្គលិក</th><th class="px-5 py-3">កំណត់</th><th class="px-5 py-3">វឌ្ឍនភាព</th><th class="px-5 py-3">ស្ថានភាព</th><th class="px-5 py-3 text-right">សកម្មភាព</th></tr></thead><tbody class="divide-y divide-zinc-100 dark:divide-zinc-800">@forelse($this->tasks as $task)<tr><td class="px-5 py-4"><div class="font-medium">{{$task->title}}</div><div class="text-xs text-zinc-500">{{$task->employee->employee_code}} — {{$task->employee->full_name_km?:$task->employee->full_name_en}}</div></td><td class="px-5 py-4">{{$task->due_date->format('d/m/Y')}}</td><td class="px-5 py-4">{{$task->progress}}%</td><td class="px-5 py-4"><flux:badge>{{$task->effective_status}}</flux:badge></td><td class="px-5 py-4">@if($task->status==='waiting_verification')<div class="flex justify-end gap-2"><flux:input size="sm" wire:model="notes.{{$task->id}}" placeholder="មតិ"/><flux:button size="sm" variant="primary" wire:click="verify({{$task->id}},true)">ទទួល</flux:button><flux:button size="sm" variant="danger" wire:click="verify({{$task->id}},false)">ត្រឡប់</flux:button></div>@endif @can('task.cancel')@if(!in_array($task->status,['verified','cancelled']))<div class="mt-2 flex justify-end gap-2"><flux:input size="sm" wire:model="cancelReasons.{{$task->id}}" placeholder="មូលហេតុលុបចោល"/><flux:button size="sm" variant="danger" wire:click="cancel({{$task->id}})">លុបចោល</flux:button></div>@endif@endcan</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-zinc-500">មិនទាន់មានកិច្ចការទេ។</td></tr>@endforelse</tbody></table></div><div class="p-4">{{$this->tasks->links()}}</div></div>
</div>
