<x-layouts::app title="Roles & permissions">
    <x-workspace-command-bar title="Roles & permissions" icon="fa-shield-halved"><x-slot:actions><button class="btn btn-action-link btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#addRole"><i class="fa-solid fa-circle-plus"></i><span>Add role</span></button></x-slot:actions></x-workspace-command-bar>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="reference-list"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-3">Role</th><th>Users</th><th>Permissions</th><th>Protection</th><th class="text-end pe-3">Actions</th></tr></thead><tbody>
        @foreach($roles as $role)<tr><td class="ps-3 fw-medium">{{ $role->name }}</td><td>{{ $role->users_count }}</td><td>{{ $role->permissions_count }}</td><td>{{ in_array($role->name, $protectedRoles, true) ? 'System protected' : 'Customizable' }}</td><td class="text-end pe-3">@if(!in_array($role->name, $protectedRoles, true))<button class="btn btn-action-link btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#editRole{{ $role->id }}"><i class="fa-solid fa-pen"></i><span>Edit</span></button><form class="d-inline" method="POST" action="{{ route('roles.destroy', $role) }}" data-confirm="Delete this role? Assigned roles cannot be deleted.">@csrf @method('DELETE')<button class="btn btn-action-link btn-sm text-danger" type="submit"><i class="fa-solid fa-trash"></i><span>Delete</span></button></form>@endif</td></tr>@endforeach
    </tbody></table></div><x-pagination-footer :paginator="$roles" /></div>
    <div class="modal fade" id="addRole" tabindex="-1"><div class="modal-dialog modal-xl"><form class="modal-content" method="POST" action="{{ route('roles.store') }}">@csrf<div class="modal-header"><h2 class="modal-title fs-5">Add role</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><x-role-fields :permissions="$permissions" /></div><x-form-save-actions save-label="Save & close" /></form></div></div>
    @foreach($roles as $role)@if(!in_array($role->name, $protectedRoles, true))<div class="modal fade" id="editRole{{ $role->id }}" tabindex="-1"><div class="modal-dialog modal-xl"><form class="modal-content" method="POST" action="{{ route('roles.update', $role) }}">@csrf @method('PUT')<div class="modal-header"><h2 class="modal-title fs-5">Edit role</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><x-role-fields :permissions="$permissions" :role="$role" /><div class="alert alert-warning mt-3 mb-0">Saving permission changes revokes sessions for users assigned to this role.</div></div><x-form-save-actions save-label="Save & close" /></form></div></div>@endif @endforeach
</x-layouts::app>
