<x-layouts::app title="Users">
    <x-workspace-command-bar title="Users" icon="fa-users-gear">
        <x-slot:filters><form class="reference-filter-form" method="GET" hx-get="{{ request()->url() }}" hx-target="[data-list-container]" hx-swap="outerHTML" hx-push-url="true"><div class="input-group reference-search"><span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search name, email, or employee ID" hx-get="{{ request()->url() }}" hx-target="[data-list-container]" hx-swap="outerHTML" hx-push-url="false" hx-trigger="keyup changed delay:500ms"></div><select class="form-select reference-status" name="status" hx-get="{{ request()->url() }}" hx-target="[data-list-container]" hx-swap="outerHTML" hx-push-url="true" hx-trigger="change"><option value="">All statuses</option><option value="1" @selected(request('status') === '1')>Active</option><option value="0" @selected(request('status') === '0')>Inactive</option></select><button class="btn btn-primary reference-search-button">Search</button></form></x-slot:filters>
        <x-slot:actions><button class="btn btn-action-link btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#addUser"><i class="fa-solid fa-circle-plus"></i><span>Add user</span></button></x-slot:actions>
    </x-workspace-command-bar>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="access-review-strip" aria-label="Access review summary"><span><strong>{{ $accessReview['privileged'] }}</strong> privileged users</span><span><strong>{{ $accessReview['dormant'] }}</strong> dormant active accounts</span><span><strong>{{ $accessReview['employees_without_accounts'] }}</strong> employees without accounts</span><span class="{{ $accessReview['separated_with_access'] ? 'text-danger' : '' }}"><strong>{{ $accessReview['separated_with_access'] }}</strong> separated employees with access</span></div>
    <div class="reference-list"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-3">User</th><th>Employee</th><th>Roles</th><th>Verification</th><th>Status</th><th class="text-end pe-3">Actions</th></tr></thead><tbody>
        @forelse($users as $user)
            <tr><td class="ps-3"><div class="fw-medium">{{ $user->name }}</div><small class="text-body-secondary">{{ $user->email }}</small></td><td>{{ $user->employee?->employee_code ? $user->employee->employee_code.' · '.($user->employee->full_name_en ?: $user->employee->first_name.' '.$user->employee->last_name) : 'Not linked' }}</td><td>@foreach($user->roles as $role)<span class="badge text-bg-light border me-1">{{ $role->name }}</span>@endforeach</td><td>{{ $user->email_verified_at ? 'Verified' : 'Pending' }}</td><td><span class="badge text-bg-{{ $user->is_active ? 'success' : 'secondary' }}">{{ $user->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end pe-3">@php($protectedAccount = $user->hasAnyRole(['Super Admin', 'Owner']) && !auth()->user()->hasRole('Super Admin')) @if(!$protectedAccount)<button class="btn btn-action-link btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#editUser{{ $user->id }}"><i class="fa-solid fa-pen"></i><span>Edit access</span></button><form class="d-inline" method="POST" action="{{ route('users.password-reset', $user) }}">@csrf<button class="btn btn-action-link btn-sm" type="submit"><i class="fa-solid fa-key"></i><span>Reset password</span></button></form>@if(!$user->is(auth()->user()))<form class="d-inline" method="POST" action="{{ route('users.status', $user) }}" data-confirm="{{ $user->is_active ? 'Deactivate this account and revoke its sessions?' : 'Reactivate this account?' }}">@csrf @method('PUT')<input type="hidden" name="is_active" value="{{ $user->is_active ? 0 : 1 }}"><button class="btn btn-action-link btn-sm {{ $user->is_active ? 'text-danger' : '' }}" type="submit"><i class="fa-solid fa-{{ $user->is_active ? 'user-lock' : 'user-check' }}"></i><span>{{ $user->is_active ? 'Deactivate' : 'Reactivate' }}</span></button></form>@endif @else<span class="small text-body-secondary">Super Admin approval required</span>@endif</td></tr>
        @empty<tr><td class="text-center text-body-secondary py-5" colspan="6">No users.</td></tr>@endforelse
    </tbody></table></div><x-pagination-footer :paginator="$users" /></div>

    <div class="modal fade" id="addUser" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('users.store') }}">@csrf<div class="modal-header"><h2 class="modal-title fs-5">Provision user account</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><x-user-access-fields :roles="$roles" :employees="$employees" /><div class="form-text mt-3">A password setup link will be sent to the user. No shared default password is created.</div></div><x-form-save-actions save-label="Provision & close" /></form></div></div>
    @foreach($users->filter(fn($user) => !$user->hasAnyRole(['Super Admin', 'Owner']) || auth()->user()->hasRole('Super Admin')) as $user)
        <div class="modal fade" id="editUser{{ $user->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('users.update', $user) }}">@csrf @method('PUT')<div class="modal-header"><h2 class="modal-title fs-5">Edit user access</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><x-user-access-fields :roles="$roles" :employees="$employees" :user="$user" /><div class="alert alert-warning mt-3 mb-0">Saving access changes revokes this user's existing sessions.</div></div><x-form-save-actions save-label="Save & close" /></form></div></div>
    @endforeach
</x-layouts::app>