<?php if (isset($component)) { $__componentOriginal81a506f898233b9e7d58286e6bea3c18 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal81a506f898233b9e7d58286e6bea3c18 = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'layouts.app','data' => ['title' => 'Create employment contract']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('layouts::app'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Create employment contract']); ?>
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><h1 class="h3 mb-1">Create employment contract</h1><p class="text-body-secondary mb-0">Save a draft and submit it for approval.</p></div><a class="btn btn-outline-secondary" href="<?php echo e(route('contracts.index')); ?>"><i class="fa-solid fa-arrow-left me-1"></i>Back to contracts</a></div>
    <?php if($errors->any()): ?><div class="alert alert-danger"><ul class="mb-0 ps-3"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
    <form class="contract-create-form" method="POST" action="<?php echo e(route('contracts.store')); ?>" enctype="multipart/form-data"><?php echo csrf_field(); ?>
        <?php if($renewal): ?><input type="hidden" name="previous_contract_id" value="<?php echo e($renewal->id); ?>"><div class="alert alert-info">Renewing contract <?php echo e($renewal->contract_number); ?>. The new term must start after <?php echo e($renewal->end_date->format('d/m/Y')); ?>.</div><?php endif; ?>
        <div class="card mb-3"><div class="card-header">Employee and contract</div><div class="card-body row g-3"><div class="col-md-6"><label class="form-label">Employee <span class="text-danger">*</span></label><select class="form-select" name="employee_id" required><option value="">Select employee</option><?php $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $employee): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($employee->id); ?>" <?php if(old('employee_id', $renewal?->employee_id) == $employee->id): echo 'selected'; endif; ?>><?php echo e($employee->employee_code); ?> — <?php echo e($employee->full_name_km ?: $employee->full_name_en); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-6"><label class="form-label">Contract number <span class="text-danger">*</span></label><input class="form-control" name="contract_number" value="<?php echo e(old('contract_number')); ?>" required></div><div class="col-md-6"><label class="form-label">Contract type <span class="text-danger">*</span></label><select class="form-select" name="type" required><option value="fdc" <?php if(old('type', $renewal ? 'fdc' : '') === 'fdc'): echo 'selected'; endif; ?>>FDC — fixed duration</option><option value="udc" <?php if(old('type') === 'udc'): echo 'selected'; endif; ?>>UDC — open-ended</option><option value="probation" <?php if(old('type') === 'probation'): echo 'selected'; endif; ?>>Probation</option><option value="apprenticeship" <?php if(old('type') === 'apprenticeship'): echo 'selected'; endif; ?>>Apprenticeship</option><option value="internship" <?php if(old('type') === 'internship'): echo 'selected'; endif; ?>>Internship</option></select></div><div class="col-md-6"><label class="form-label">Signed document (PDF, max. 10 MB)</label><input class="form-control" type="file" name="document" accept=".pdf"></div></div></div>
        <div class="card mb-3"><div class="card-header">Term and probation</div><div class="card-body row g-3"><div class="col-md-4"><label class="form-label">Start date</label><input class="form-control" type="date" name="start_date" value="<?php echo e(old('start_date', $renewal?->end_date?->copy()->addDay()->toDateString())); ?>" required></div><div class="col-md-4"><label class="form-label">End date</label><input class="form-control" type="date" name="end_date" value="<?php echo e(old('end_date')); ?>"></div><div class="col-md-4"><label class="form-label">Signed date</label><input class="form-control" type="date" name="signed_at" value="<?php echo e(old('signed_at')); ?>"></div><div class="col-md-6"><label class="form-label">Probation category</label><select class="form-select" name="probation_category"><option value="">Not applicable</option><option value="regular" <?php if(old('probation_category') === 'regular'): echo 'selected'; endif; ?>>Regular</option><option value="specialized" <?php if(old('probation_category') === 'specialized'): echo 'selected'; endif; ?>>Specialized</option><option value="non_specialized" <?php if(old('probation_category') === 'non_specialized'): echo 'selected'; endif; ?>>Non-specialized</option></select></div><div class="col-md-6"><label class="form-label">Probation end date</label><input class="form-control" type="date" name="probation_end_date" value="<?php echo e(old('probation_end_date')); ?>"></div></div></div>
        <div class="card"><div class="card-header">Salary and working time</div><div class="card-body row g-3"><div class="col-md-4"><label class="form-label">Salary amount</label><input class="form-control" type="number" step="0.01" min="0" name="salary_amount" value="<?php echo e(old('salary_amount', $renewal?->salary_amount)); ?>" required></div><div class="col-md-4"><label class="form-label">Currency</label><select class="form-select" name="salary_currency"><option value="USD" <?php if(old('salary_currency', $renewal?->salary_currency ?? 'USD') === 'USD'): echo 'selected'; endif; ?>>USD</option><option value="KHR" <?php if(old('salary_currency', $renewal?->salary_currency) === 'KHR'): echo 'selected'; endif; ?>>KHR</option></select></div><div class="col-md-4"><label class="form-label">Pay type</label><select class="form-select" name="pay_type"><option value="monthly" <?php if(old('pay_type', $renewal?->pay_type ?? 'monthly') === 'monthly'): echo 'selected'; endif; ?>>Monthly</option><option value="daily" <?php if(old('pay_type') === 'daily'): echo 'selected'; endif; ?>>Daily</option><option value="hourly" <?php if(old('pay_type') === 'hourly'): echo 'selected'; endif; ?>>Hourly</option></select></div><div class="col-md-6"><label class="form-label">Work hours per day</label><input class="form-control" type="number" step="0.25" min="1" max="24" name="work_hours_per_day" value="<?php echo e(old('work_hours_per_day', $renewal?->work_hours_per_day ?? 8)); ?>" required></div><div class="col-md-6"><label class="form-label">Work days per week</label><input class="form-control" type="number" step="0.5" min="1" max="7" name="work_days_per_week" value="<?php echo e(old('work_days_per_week', $renewal?->work_days_per_week ?? 6)); ?>" required></div></div><div class="card-footer bg-white text-end"><a class="btn btn-light" href="<?php echo e(route('contracts.index')); ?>">Cancel</a><button class="btn btn-primary" type="submit"><i class="fa-solid fa-paper-plane me-1"></i>Save and submit</button></div></div>
        <div class="form-page-actions d-flex justify-content-end gap-2 pt-3"><a class="btn btn-light" href="<?php echo e(route('contracts.index')); ?>">Close</a><button class="btn btn-primary" type="submit"><i class="fa-solid fa-paper-plane me-1"></i>Save and submit</button></div>
    </form>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal81a506f898233b9e7d58286e6bea3c18)): ?>
<?php $attributes = $__attributesOriginal81a506f898233b9e7d58286e6bea3c18; ?>
<?php unset($__attributesOriginal81a506f898233b9e7d58286e6bea3c18); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal81a506f898233b9e7d58286e6bea3c18)): ?>
<?php $component = $__componentOriginal81a506f898233b9e7d58286e6bea3c18; ?>
<?php unset($__componentOriginal81a506f898233b9e7d58286e6bea3c18); ?>
<?php endif; ?>
<?php /**PATH D:\www\bizhr\resources\views\pages\employment-contracts\create.blade.php ENDPATH**/ ?>