<?php
use App\Models\Employee; use App\Models\TrainingCourse; use App\Models\TrainingEnrollment;
use Livewire\Attributes\Computed; use Livewire\Attributes\Title; use Livewire\Component;
new #[Title('ការបណ្តុះបណ្តាល')] class extends Component {
 public string $title='',$description='',$courseId='',$employeeId='',$dueDate=''; public int $duration=60; public bool $mandatory=false;
 #[Computed] public function courses(){return TrainingCourse::withCount('enrollments')->latest()->get();}
 #[Computed] public function employees(){return Employee::active()->orderBy('employee_code')->get();}
 #[Computed] public function enrollments(){return TrainingEnrollment::with(['course','employee'])->latest()->limit(100)->get();}
 public function saveCourse():void{abort_unless(auth()->user()->can('training.manage'),403);$d=$this->validate(['title'=>'required|string|max:180','description'=>'nullable|string|max:5000','duration'=>'required|integer|min:1|max:100000']);TrainingCourse::create(['company_id'=>auth()->user()->employee?->company_id ?? \App\Models\Company::query()->value('id'),'title'=>$d['title'],'description'=>$d['description']?:null,'duration_minutes'=>$d['duration'],'is_mandatory'=>$this->mandatory,'created_by'=>auth()->id()]);$this->reset(['title','description','mandatory']);unset($this->courses);}
 public function assign():void{abort_unless(auth()->user()->can('training.manage'),403);$d=$this->validate(['courseId'=>'required|exists:training_courses,id','employeeId'=>'required|exists:employees,id','dueDate'=>'nullable|date|after_or_equal:today']);TrainingEnrollment::updateOrCreate(['training_course_id'=>$d['courseId'],'employee_id'=>$d['employeeId']],['status'=>'assigned','progress'=>0,'due_date'=>$d['dueDate']?:null,'assigned_by'=>auth()->id()]);$this->reset(['courseId','employeeId','dueDate']);unset($this->enrollments);}
}; ?>
<div class="space-y-6"><div><flux:heading size="xl">ការបណ្តុះបណ្តាល</flux:heading><flux:subheading>បង្កើតវគ្គ ផ្តល់ការសិក្សា និងតាមដានលទ្ធផល</flux:subheading></div>
<div class="grid gap-5 xl:grid-cols-2"><form wire:submit="saveCourse" class="space-y-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><flux:heading>វគ្គថ្មី</flux:heading><flux:input wire:model="title" label="ឈ្មោះវគ្គ *"/><flux:textarea wire:model="description" label="ពិពណ៌នា"/><flux:input wire:model="duration" type="number" label="រយៈពេល (នាទី) *"/><flux:checkbox wire:model="mandatory" label="វគ្គចាំបាច់"/><flux:button type="submit" variant="primary">រក្សាទុក</flux:button></form><form wire:submit="assign" class="space-y-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><flux:heading>ផ្តល់វគ្គឱ្យបុគ្គលិក</flux:heading><flux:select wire:model="courseId" label="វគ្គ *"><option value="">ជ្រើសរើស</option>@foreach($this->courses as $c)<option value="{{$c->id}}">{{$c->title}}</option>@endforeach</flux:select><flux:select wire:model="employeeId" label="បុគ្គលិក *"><option value="">ជ្រើសរើស</option>@foreach($this->employees as $e)<option value="{{$e->id}}">{{$e->employee_code}} — {{$e->full_name_km?:$e->full_name_en}}</option>@endforeach</flux:select><flux:input wire:model="dueDate" type="date" label="ថ្ងៃកំណត់"/><flux:button type="submit" variant="primary">ផ្តល់វគ្គ</flux:button></form></div>
<div class="overflow-x-auto rounded-2xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><table class="min-w-full"><thead><tr class="text-left"><th class="p-4">បុគ្គលិក</th><th class="p-4">វគ្គ</th><th class="p-4">វឌ្ឍនភាព</th><th class="p-4">កំណត់</th><th class="p-4">ស្ថានភាព</th></tr></thead><tbody>@foreach($this->enrollments as $x)<tr class="border-t border-zinc-200 dark:border-zinc-800"><td class="p-4">{{$x->employee->full_name_km?:$x->employee->full_name_en}}</td><td class="p-4">{{$x->course->title}}</td><td class="p-4">{{$x->progress}}%</td><td class="p-4">{{$x->due_date?->format('d/m/Y')??'—'}}</td><td class="p-4"><flux:badge>{{$x->status}}</flux:badge></td></tr>@endforeach</tbody></table></div></div>
