<?php
use App\Models\ExpenseClaim; use App\Services\ExpenseWorkflowService;
use Livewire\Attributes\Computed; use Livewire\Attributes\Title; use Livewire\Component; use Livewire\WithPagination;
new #[Title('សំណងចំណាយ')] class extends Component {
 use WithPagination; public string $status=''; public array $notes=[],$references=[];
 #[Computed] public function claims(){return ExpenseClaim::with('employee')->when($this->status,fn($q)=>$q->where('status',$this->status))->latest()->paginate(25);}
 public function manager(int $id,bool $ok,ExpenseWorkflowService $s):void{abort_unless(auth()->user()->can('expense.approve-manager'),403);try{$s->managerReview(ExpenseClaim::findOrFail($id),auth()->user(),$ok,$this->notes[$id]??'');}catch(\DomainException $e){$this->addError('workflow',$e->getMessage());return;}unset($this->claims);}
 public function accounting(int $id,bool $ok,ExpenseWorkflowService $s):void{abort_unless(auth()->user()->can('expense.approve-accounting'),403);try{$s->accountingReview(ExpenseClaim::findOrFail($id),auth()->user(),$ok,$this->notes[$id]??'');}catch(\DomainException $e){$this->addError('workflow',$e->getMessage());return;}unset($this->claims);}
 public function pay(int $id,ExpenseWorkflowService $s):void{abort_unless(auth()->user()->can('expense.pay'),403);try{$s->markPaid(ExpenseClaim::findOrFail($id),auth()->user(),$this->references[$id]??'');}catch(\DomainException $e){$this->addError('workflow',$e->getMessage());return;}unset($this->claims);}
}; ?>
<div class="space-y-6"><div class="flex justify-between"><div><flux:heading size="xl">ពិនិត្យសំណងចំណាយ</flux:heading><flux:subheading>Manager → Accounting → Paid ដោយហាមអនុម័តខ្លួនឯង</flux:subheading></div><flux:select wire:model.live="status" class="max-w-56"><option value="">គ្រប់ស្ថានភាព</option>@foreach(['pending_manager','pending_accounting','approved','paid','rejected'] as $s)<option value="{{$s}}">{{$s}}</option>@endforeach</flux:select></div>@error('workflow')<div class="rounded-xl bg-red-50 p-4 text-red-700">{{$message}}</div>@enderror
<div class="overflow-x-auto rounded-2xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><table class="min-w-full"><thead><tr class="text-left"><th class="p-4">បុគ្គលិក/គោលបំណង</th><th class="p-4">ចំនួន</th><th class="p-4">ស្ថានភាព</th><th class="p-4">សកម្មភាព</th></tr></thead><tbody>@forelse($this->claims as $x)<tr class="border-t border-zinc-200 dark:border-zinc-800"><td class="p-4"><div class="font-medium">{{$x->employee->full_name_km?:$x->employee->full_name_en}}</div><div class="text-xs text-zinc-500">{{$x->business_purpose}}</div></td><td class="p-4 font-medium">{{number_format($x->amount,2)}} {{$x->currency}}</td><td class="p-4"><flux:badge>{{$x->status}}</flux:badge></td><td class="p-4"><div class="flex min-w-96 gap-2">@if(in_array($x->status,['pending_manager','pending_accounting']))<flux:input size="sm" wire:model="notes.{{$x->id}}" placeholder="មតិ"/>@endif @if($x->status==='pending_manager'&&auth()->user()->can('expense.approve-manager'))<flux:button size="sm" variant="primary" wire:click="manager({{$x->id}},true)">អនុម័ត</flux:button><flux:button size="sm" variant="danger" wire:click="manager({{$x->id}},false)">បដិសេធ</flux:button>@elseif($x->status==='pending_accounting'&&auth()->user()->can('expense.approve-accounting'))<flux:button size="sm" variant="primary" wire:click="accounting({{$x->id}},true)">អនុម័តគណនេយ្យ</flux:button><flux:button size="sm" variant="danger" wire:click="accounting({{$x->id}},false)">បដិសេធ</flux:button>@elseif($x->status==='approved'&&auth()->user()->can('expense.pay'))<flux:input size="sm" wire:model="references.{{$x->id}}" placeholder="Payment reference"/><flux:button size="sm" variant="primary" wire:click="pay({{$x->id}})">កត់ថាបានបង់</flux:button>@endif</div></td></tr>@empty<tr><td colspan="4" class="p-10 text-center text-zinc-500">មិនមានសំណើ។</td></tr>@endforelse</tbody></table><div class="p-4">{{$this->claims->links()}}</div></div></div>
