<?php
use App\Models\ExpenseClaim; use Livewire\Attributes\Computed; use Livewire\Attributes\Title; use Livewire\Component; use Livewire\WithFileUploads;
new #[Title('ចំណាយរបស់ខ្ញុំ')] class extends Component {
 use WithFileUploads; public string $date='',$category='',$amount='',$currency='USD',$purpose=''; public $receipt;
 public function mount():void{$this->date=today()->toDateString();}
 #[Computed] public function claims(){return ExpenseClaim::where('employee_id',auth()->user()->employee?->id??0)->latest()->get();}
 public function submit():void{$employee=auth()->user()->employee;abort_unless($employee,403);$d=$this->validate(['date'=>'required|date|before_or_equal:today','category'=>'required|string|max:100','amount'=>'required|numeric|min:0.01','currency'=>'required|in:USD,KHR','purpose'=>'required|string|min:10|max:2000','receipt'=>'required|file|mimes:pdf,jpg,jpeg,png|max:5120']);$path=$this->receipt->store("private/expenses/{$employee->id}");ExpenseClaim::create(['company_id'=>$employee->company_id,'employee_id'=>$employee->id,'expense_date'=>$d['date'],'category'=>$d['category'],'amount'=>$d['amount'],'currency'=>$d['currency'],'business_purpose'=>$d['purpose'],'receipt_path'=>$path,'receipt_original_name'=>$this->receipt->getClientOriginalName()]);$this->reset(['category','amount','purpose','receipt']);unset($this->claims);session()->flash('success','បានដាក់សំណើចំណាយ។');}
}; ?>
<div class="space-y-6"><div><flux:heading size="xl">ចំណាយរបស់ខ្ញុំ</flux:heading><flux:subheading>ដាក់បង្កាន់ដៃ និងតាមដានការអនុម័ត</flux:subheading></div>@if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-green-800">{{session('success')}}</div>@endif
<form wire:submit="submit" class="grid gap-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900 md:grid-cols-2 xl:grid-cols-3"><flux:input wire:model="date" type="date" label="ថ្ងៃចំណាយ *"/><flux:input wire:model="category" label="ប្រភេទ *"/><div class="grid grid-cols-[1fr_110px] gap-3"><flux:input wire:model="amount" type="number" step="0.01" label="ចំនួន *"/><flux:select wire:model="currency" label="រូបិយប័ណ្ណ"><option>USD</option><option>KHR</option></flux:select></div><div class="md:col-span-2"><flux:textarea wire:model="purpose" label="គោលបំណងអាជីវកម្ម *"/></div><flux:input wire:model="receipt" type="file" label="បង្កាន់ដៃ PDF/JPG/PNG *"/><div class="md:col-span-2 xl:col-span-3 flex justify-end"><flux:button type="submit" variant="primary">ដាក់សំណើ</flux:button></div></form>
<div class="grid gap-4 lg:grid-cols-2">@foreach($this->claims as $x)<div class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><div class="flex justify-between"><div class="font-medium">{{$x->category}} · {{number_format($x->amount,2)}} {{$x->currency}}</div><flux:badge>{{$x->status}}</flux:badge></div><div class="mt-2 text-sm text-zinc-500">{{$x->expense_date->format('d/m/Y')}} · {{$x->business_purpose}}</div>@if($x->review_note)<div class="mt-3 rounded-lg bg-zinc-50 p-3 text-sm dark:bg-zinc-800">{{$x->review_note}}</div>@endif</div>@endforeach</div></div>
