@php($id = $type?->id ?? 'new')
<div class="row g-3">
    <div class="col-md-8"><label class="form-label" for="leave-name-{{ $id }}">Name <span class="text-danger">*</span></label><input id="leave-name-{{ $id }}" class="form-control" name="name" value="{{ old('name', $type?->name) }}" maxlength="120" required></div>
    <div class="col-md-4"><label class="form-label" for="leave-code-{{ $id }}">Code</label><input id="leave-code-{{ $id }}" class="form-control text-uppercase" name="code" value="{{ old('code', $type?->code) }}" maxlength="50" placeholder="auto-generate"></div>
    <div class="col-md-6"><label class="form-label" for="leave-days-{{ $id }}">Annual entitlement <span class="text-danger">*</span></label><div class="input-group"><input id="leave-days-{{ $id }}" class="form-control" name="days_per_year" type="number" min="0" max="366" step="0.5" value="{{ old('days_per_year', $type?->days_per_year ?? 0) }}" required><span class="input-group-text">days</span></div><div class="form-text">Set the approved company entitlement. Accrual rules need to be set in the leave-policy review.</div></div>
    <div class="col-md-6"><label class="form-label" for="leave-carry-{{ $id }}">Maximum carry forward</label><div class="input-group"><input id="leave-carry-{{ $id }}" class="form-control" name="maximum_carry_forward_days" type="number" min="0" max="366" step="0.5" value="{{ old('maximum_carry_forward_days', $type?->maximum_carry_forward_days ?? 0) }}"><span class="input-group-text">days</span></div></div>
    <div class="col-12"><div class="row g-2"><div class="col-md-6"><div class="form-check"><input class="form-check-input" type="hidden" name="is_paid" value="0"><input class="form-check-input" id="leave-paid-{{ $id }}" type="checkbox" name="is_paid" value="1" @checked(old('is_paid', $type?->is_paid ?? true))><label class="form-check-label" for="leave-paid-{{ $id }}">Paid leave</label></div><div class="form-check"><input class="form-check-input" type="hidden" name="requires_attachment" value="0"><input class="form-check-input" id="leave-attachment-{{ $id }}" type="checkbox" name="requires_attachment" value="1" @checked(old('requires_attachment', $type?->requires_attachment ?? false))><label class="form-check-label" for="leave-attachment-{{ $id }}">Require supporting document</label></div></div><div class="col-md-6"><div class="form-check"><input class="form-check-input" type="hidden" name="carry_forward_allowed" value="0"><input class="form-check-input" id="leave-forward-{{ $id }}" type="checkbox" name="carry_forward_allowed" value="1" @checked(old('carry_forward_allowed', $type?->carry_forward_allowed ?? false))><label class="form-check-label" for="leave-forward-{{ $id }}">Allow carry forward</label></div><div class="form-check"><input class="form-check-input" type="hidden" name="is_active" value="0"><input class="form-check-input" id="leave-active-{{ $id }}" type="checkbox" name="is_active" value="1" @checked(old('is_active', $type?->is_active ?? true))><label class="form-check-label" for="leave-active-{{ $id }}">Active and available to employees</label></div></div></div></div>
    <div class="col-12"><div class="form-check border-top pt-3"><input type="hidden" name="is_statutory_annual_leave" value="0"><input class="form-check-input" id="leave-statutory-{{ $id }}" type="checkbox" name="is_statutory_annual_leave" value="1" @checked(old('is_statutory_annual_leave', $type?->is_statutory_annual_leave ?? false))><label class="form-check-label fw-medium" for="leave-statutory-{{ $id }}">Cambodian statutory annual leave policy</label><div class="form-text">Requires at least 18 days per year and accrues monthly from the employee's hire date. Use this for the legal annual-leave policy only.</div></div></div>
</div>
