<x-layouts::app title="Branches">
    <x-workspace-command-bar title="Branches" icon="fa-code-branch">
        <x-slot:filters><form class="reference-filter-form" method="GET" hx-get="{{ request()->url() }}" hx-target="[data-list-container]" hx-swap="outerHTML" hx-push-url="true"><div class="input-group reference-search"><span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search branch, code or city" hx-get="{{ request()->url() }}" hx-target="[data-list-container]" hx-swap="outerHTML" hx-push-url="false" hx-trigger="keyup changed delay:500ms"></div><select class="form-select reference-status" name="status" hx-get="{{ request()->url() }}" hx-target="[data-list-container]" hx-swap="outerHTML" hx-push-url="true" hx-trigger="change"><option value="">All statuses</option><option value="1" @selected(request('status') === '1')>Active</option><option value="0" @selected(request('status') === '0')>Inactive</option></select><button class="btn btn-primary reference-search-button">Search</button></form></x-slot:filters>
        <x-slot:actions><x-list-actions :add-target="auth()->user()->can('branch.create') ? '#branchForm' : null" add-label="Add branch" /></x-slot:actions>
    </x-workspace-command-bar>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="reference-list" data-list-container><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th class="ps-3">Branch</th><th>Manager</th><th>Contact</th><th>Employees</th><th>Status</th><th class="text-end pe-3">Actions</th></tr></thead><tbody>
        @forelse($branches as $branch)<tr><td class="ps-3"><div class="fw-medium">{{ $branch->name }}</div><small class="text-body-secondary">{{ $branch->code }} · {{ $branch->city }}</small></td><td>{{ $branch->manager_name ?: '—' }}</td><td>{{ $branch->phone ?: $branch->email ?: '—' }}</td><td>{{ $branch->employees_count }}</td><td>@if($branch->is_head_office)<span class="badge text-bg-primary">Head office</span>@endif <span class="badge text-bg-{{ $branch->is_active ? 'success' : 'secondary' }}">{{ $branch->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end pe-3">@can('branch.edit')<button class="btn btn-action-link btn-sm" data-bs-toggle="modal" data-bs-target="#editBranch{{ $branch->id }}"><i class="fa-solid fa-pen"></i><span>Edit</span></button>@endcan @can('branch.delete')<form class="d-inline" method="POST" action="{{ route('branches.destroy',$branch) }}" onsubmit="return confirm('Delete this unreferenced branch?')">@csrf @method('DELETE')<button class="btn btn-action-link btn-sm text-danger"><i class="fa-solid fa-trash"></i><span>Delete</span></button></form>@endcan</td></tr>
        @empty<tr><td class="text-center text-body-secondary py-5" colspan="6">No branches.</td></tr>@endforelse
    </tbody></table></div><x-pagination-footer :paginator="$branches" /></div>
    @can('branch.create')<div class="modal fade" id="branchForm" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('branches.store') }}">@csrf<div class="modal-header"><h2 class="modal-title fs-5">Add branch</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Name <span class="text-danger">*</span></label><input class="form-control" name="name" required></div><div class="col-md-6"><label class="form-label">Code</label><input class="form-control" name="code" placeholder="auto-generate"></div><div class="col-md-6"><label class="form-label">Manager</label><input class="form-control" name="manager_name"></div><div class="col-md-6"><label class="form-label">City</label><input class="form-control" name="city"></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email"></div><div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address"></textarea></div><div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_head_office" value="1"><span class="form-check-label">Head office</span></label><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" checked><span class="form-check-label">Active</span></label></div></div></div><x-form-save-actions :allow-save-new="true" save-label="Save & close" new-label="Save & new" /></form></div></div>@endcan
    @can('branch.edit')
        @foreach($branches as $branch)<div class="modal fade" id="editBranch{{ $branch->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('branches.update',$branch) }}">@csrf @method('PUT')<div class="modal-header"><h2 class="modal-title fs-5">Edit branch</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Name</label><input class="form-control mb-3" name="name" value="{{ $branch->name }}" required><label class="form-label">Code</label><input class="form-control mb-3" name="code" value="{{ $branch->code }}" placeholder="auto-generate"><label class="form-label">Manager</label><input class="form-control mb-3" name="manager_name" value="{{ $branch->manager_name }}"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_head_office" value="1" @checked($branch->is_head_office)><span class="form-check-label">Head office</span></label><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked($branch->is_active)><span class="form-check-label">Active</span></label></div><x-form-save-actions save-label="Save & close" /></form></div></div>@endforeach
    @endcan
</x-layouts::app>