<?php
use App\Models\Asset; use App\Models\AssetAssignment; use App\Models\Employee; use App\Services\AssetWorkflowService;
use Livewire\Attributes\Computed; use Livewire\Attributes\Title; use Livewire\Component;
new #[Title('ទ្រព្យសម្បត្តិ')] class extends Component {
 public string $code='',$name='',$category='',$serial='',$currency='USD',$cost='',$assetId='',$employeeId='',$dueDate='',$condition='good'; public array $returnCondition=[];
 #[Computed] public function assets(){return Asset::latest()->get();} #[Computed] public function employees(){return Employee::active()->orderBy('employee_code')->get();} #[Computed] public function assignments(){return AssetAssignment::with(['asset','employee'])->latest()->limit(100)->get();}
 public function save():void{abort_unless(auth()->user()->can('asset.manage'),403);$d=$this->validate(['code'=>'required|max:50','name'=>'required|max:180','category'=>'required|max:100','serial'=>'nullable|max:120','currency'=>'required|in:USD,KHR','cost'=>'nullable|numeric|min:0']);Asset::create(['company_id'=>auth()->user()->employee?->company_id ?? \App\Models\Company::query()->value('id'),'asset_code'=>$d['code'],'name'=>$d['name'],'category'=>$d['category'],'serial_number'=>$d['serial']?:null,'currency'=>$d['currency'],'purchase_cost'=>$d['cost']?:null]);$this->reset(['code','name','category','serial','cost']);unset($this->assets);}
 public function assign(AssetWorkflowService $s):void{abort_unless(auth()->user()->can('asset.manage'),403);$d=$this->validate(['assetId'=>'required|exists:assets,id','employeeId'=>'required|exists:employees,id','condition'=>'required|in:new,good,fair,damaged','dueDate'=>'nullable|date|after_or_equal:today']);try{$s->assign(Asset::findOrFail($d['assetId']),Employee::findOrFail($d['employeeId']),auth()->user(),$d['condition'],$d['dueDate']?:null);}catch(\DomainException $e){$this->addError('workflow',$e->getMessage());return;}$this->reset(['assetId','employeeId','dueDate']);unset($this->assets,$this->assignments);}
 public function receive(int $id,AssetWorkflowService $s):void{abort_unless(auth()->user()->can('asset.manage'),403);try{$s->receive(AssetAssignment::findOrFail($id),auth()->user(),$this->returnCondition[$id]??'good',null);}catch(\DomainException $e){$this->addError('workflow',$e->getMessage());return;}unset($this->assets,$this->assignments);}
}; ?>
<div class="space-y-6"><div><flux:heading size="xl">គ្រប់គ្រងទ្រព្យសម្បត្តិ</flux:heading><flux:subheading>ចុះបញ្ជី ប្រគល់ និងទទួលទ្រព្យត្រឡប់ដោយរក្សាប្រវត្តិ</flux:subheading></div>@error('workflow')<div class="rounded-xl bg-red-50 p-4 text-red-700">{{$message}}</div>@enderror
<div class="grid gap-5 xl:grid-cols-2"><form wire:submit="save" class="grid gap-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900 sm:grid-cols-2"><flux:heading class="sm:col-span-2">ទ្រព្យថ្មី</flux:heading><flux:input wire:model="code" label="លេខកូដ *"/><flux:input wire:model="name" label="ឈ្មោះ *"/><flux:input wire:model="category" label="ប្រភេទ *"/><flux:input wire:model="serial" label="Serial"/><flux:select wire:model="currency" label="រូបិយប័ណ្ណ"><option>USD</option><option>KHR</option></flux:select><flux:input wire:model="cost" type="number" step="0.01" label="តម្លៃ"/><flux:button type="submit" variant="primary">រក្សាទុក</flux:button></form><form wire:submit="assign" class="space-y-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-700 dark:bg-zinc-900"><flux:heading>ប្រគល់ទ្រព្យ</flux:heading><flux:select wire:model="assetId" label="ទ្រព្យ *"><option value="">ជ្រើសរើស</option>@foreach($this->assets->where('status','available') as $a)<option value="{{$a->id}}">{{$a->asset_code}} — {{$a->name}}</option>@endforeach</flux:select><flux:select wire:model="employeeId" label="បុគ្គលិក *"><option value="">ជ្រើសរើស</option>@foreach($this->employees as $e)<option value="{{$e->id}}">{{$e->employee_code}} — {{$e->full_name_km?:$e->full_name_en}}</option>@endforeach</flux:select><div class="grid grid-cols-2 gap-4"><flux:select wire:model="condition" label="សភាព"><option value="new">ថ្មី</option><option value="good">ល្អ</option><option value="fair">មធ្យម</option><option value="damaged">ខូច</option></flux:select><flux:input wire:model="dueDate" type="date" label="ថ្ងៃត្រឡប់"/></div><flux:button type="submit" variant="primary">ប្រគល់</flux:button></form></div>
<div class="overflow-x-auto rounded-2xl border border-zinc-200 bg-white dark:border-zinc-700 dark:bg-zinc-900"><table class="min-w-full"><thead><tr class="text-left"><th class="p-4">ទ្រព្យ</th><th class="p-4">បុគ្គលិក</th><th class="p-4">ថ្ងៃប្រគល់</th><th class="p-4">ស្ថានភាព</th><th class="p-4">សកម្មភាព</th></tr></thead><tbody>@foreach($this->assignments as $x)<tr class="border-t border-zinc-200 dark:border-zinc-800"><td class="p-4">{{$x->asset->asset_code}} — {{$x->asset->name}}</td><td class="p-4">{{$x->employee->full_name_km?:$x->employee->full_name_en}}</td><td class="p-4">{{$x->assigned_date->format('d/m/Y')}}</td><td class="p-4"><flux:badge>{{$x->status}}</flux:badge></td><td class="p-4">@if($x->status==='assigned')<div class="flex gap-2"><flux:select size="sm" wire:model="returnCondition.{{$x->id}}"><option value="good">ល្អ</option><option value="fair">មធ្យម</option><option value="damaged">ខូច</option><option value="lost">បាត់</option><option value="retired">ដកចេញ</option></flux:select><flux:button size="sm" wire:click="receive({{$x->id}})">ទទួលត្រឡប់</flux:button></div>@endif</td></tr>@endforeach</tbody></table></div></div>
